//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUserContorls.Web.ServiceReference_FilesTransport {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_FilesTransport.FilesTransportSoap")]
    public interface FilesTransportSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        // CODEGEN: 参数“myFileStream”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUserContorls.Web.ServiceReference_FilesTransport.UploadResponse Upload(WebUserContorls.Web.ServiceReference_FilesTransport.UploadRequest request);
        
        // CODEGEN: 参数“DownLoadResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownLoad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadResponse DownLoad(WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFilesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFilesList(string myFileName, string myFileGroupId, string myFileClassify, string myKeyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(string myFileItemId, string myFileClassify, string myFilePath, string myKeyId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Upload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] myFileStream;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myFileGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string myFileClassify;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public float myFileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string myFilePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string myFileType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string myKeyId;
        
        public UploadRequest() {
        }
        
        public UploadRequest(byte[] myFileStream, string myFileName, string myFileGroupId, string myFileClassify, float myFileSize, string myFilePath, string myFileType, string myKeyId) {
            this.myFileStream = myFileStream;
            this.myFileName = myFileName;
            this.myFileGroupId = myFileGroupId;
            this.myFileClassify = myFileClassify;
            this.myFileSize = myFileSize;
            this.myFilePath = myFilePath;
            this.myFileType = myFileType;
            this.myKeyId = myKeyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UploadResult;
        
        public UploadResponse() {
        }
        
        public UploadResponse(int UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownLoad", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownLoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string myFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string myFilePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string myKeyId;
        
        public DownLoadRequest() {
        }
        
        public DownLoadRequest(string myFileName, string myFilePath, string myKeyId) {
            this.myFileName = myFileName;
            this.myFilePath = myFilePath;
            this.myKeyId = myKeyId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownLoadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownLoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownLoadResult;
        
        public DownLoadResponse() {
        }
        
        public DownLoadResponse(byte[] DownLoadResult) {
            this.DownLoadResult = DownLoadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilesTransportSoapChannel : WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilesTransportSoapClient : System.ServiceModel.ClientBase<WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap>, WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap {
        
        public FilesTransportSoapClient() {
        }
        
        public FilesTransportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilesTransportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesTransportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesTransportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUserContorls.Web.ServiceReference_FilesTransport.UploadResponse WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap.Upload(WebUserContorls.Web.ServiceReference_FilesTransport.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public int Upload(byte[] myFileStream, string myFileName, string myFileGroupId, string myFileClassify, float myFileSize, string myFilePath, string myFileType, string myKeyId) {
            WebUserContorls.Web.ServiceReference_FilesTransport.UploadRequest inValue = new WebUserContorls.Web.ServiceReference_FilesTransport.UploadRequest();
            inValue.myFileStream = myFileStream;
            inValue.myFileName = myFileName;
            inValue.myFileGroupId = myFileGroupId;
            inValue.myFileClassify = myFileClassify;
            inValue.myFileSize = myFileSize;
            inValue.myFilePath = myFilePath;
            inValue.myFileType = myFileType;
            inValue.myKeyId = myKeyId;
            WebUserContorls.Web.ServiceReference_FilesTransport.UploadResponse retVal = ((WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap)(this)).Upload(inValue);
            return retVal.UploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadResponse WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap.DownLoad(WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadRequest request) {
            return base.Channel.DownLoad(request);
        }
        
        public byte[] DownLoad(string myFileName, string myFilePath, string myKeyId) {
            WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadRequest inValue = new WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadRequest();
            inValue.myFileName = myFileName;
            inValue.myFilePath = myFilePath;
            inValue.myKeyId = myKeyId;
            WebUserContorls.Web.ServiceReference_FilesTransport.DownLoadResponse retVal = ((WebUserContorls.Web.ServiceReference_FilesTransport.FilesTransportSoap)(this)).DownLoad(inValue);
            return retVal.DownLoadResult;
        }
        
        public System.Data.DataTable GetFilesList(string myFileName, string myFileGroupId, string myFileClassify, string myKeyId) {
            return base.Channel.GetFilesList(myFileName, myFileGroupId, myFileClassify, myKeyId);
        }
        
        public int Delete(string myFileItemId, string myFileClassify, string myFilePath, string myKeyId) {
            return base.Channel.Delete(myFileItemId, myFileClassify, myFilePath, myKeyId);
        }
    }
}
